### ISSUE TITLE
[16.0] Assistance Required for EDI Process sale orders from ext storage

### ISSUE THREAD

**Issue by Hbohry** [OCA/edi-framework#121]
**EDIT: Odoo 16.0 EE**

We are currently facing some difficulties in setting up the EDI process on Odoo and need your assistance to move forward. 

Here is what we've done so far:

To implement the EDI process, we have cloned all the modules into the EDI Framework repository.

We have watched the OCA Days videos on EDI (2021, 2022, and 2023).

Our goal is to create a quote automatically on Odoo from FTP, and we believe the EDI modules should handle this task.

We have followed these steps:

- Configuration of the FTP server.

- Configuration of EDI Backend and EDI Backend Type.

- Configuration of Exchange Type and its component:

```
components:
    process:
        usage: input.process.sale.order
sale_order:
        confirm_order: true
```

- Manual execution of the cron: "EDI exchange check input sync".

However, we are currently stuck and do not know what to do next to make the import work.

Could you please guide us on how to proceed or provide any assistance to help us resolve this issue?

Below you can find some details explaining our setup :

**FTP server configuration** 
![FTP](https://github.com/user-attachments/assets/5be27da6-76dc-404e-8777-9f0838e43c45)

**Configuration EDI BACKEND :**
![backend](https://github.com/user-attachments/assets/67df4e16-51f1-4e0f-9fc3-8c3da4d2bbf4)
![backen-type](https://github.com/user-attachments/assets/704c2f78-ab53-43f3-bcaa-892a40daff21)

**Configuration EDI Exchange type :**
![exchange-type](https://github.com/user-attachments/assets/08694f0c-1de0-4c31-a74e-c754895a043f)
![component](https://github.com/user-attachments/assets/c28da75d-5e10-4c49-ab7b-1c02c88d0694)
![rule](https://github.com/user-attachments/assets/2413b2ab-35fa-4a8e-9d44-2a5f35840918)

**All  the resulting job queues are failed :**
![queue-job](https://github.com/user-attachments/assets/bcd43d1c-4115-41a9-9476-46a596f4824f)

In addition to that , all the exchanges records created are either pending or doesn't have any files 
![EDI-exchange](https://github.com/user-attachments/assets/edb4b2c2-bed4-40d7-81d8-b14dd3e2bed2)

Thank you very much for your support.

**Comment by simahawk** [comment]
Failed jobs: how? What's the error?

**Comment by Hbohry** [comment]
![Uploading failed.png…]()

**Comment by Hbohry** [comment]
this is the error message 
![failed](https://github.com/user-attachments/assets/2d36f93c-75d5-4877-8324-d9fbf1f7c9e1)

**Comment by simahawk** [comment]
@Hbohry sorry but the only relevant part at the bottom is cut :)

**Comment by Hbohry** [comment]
Exception:NotImplementedError
Traceback (most recent call last):
  File "/home/hbohry/workspace/odoo_17/third-party/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/home/hbohry/workspace/odoo_17/third-party/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/home/hbohry/workspace/odoo_17/third-party/queue_job/job.py", line 522, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/home/hbohry/workspace/odoo_17/third-party/edi_oca/models/edi_exchange_record.py", line 331, in action_exchange_receive
    return self.backend_id.exchange_receive(self)
  File "/home/hbohry/workspace/odoo_17/third-party/edi_oca/models/edi_backend.py", line 549, in exchange_receive
    content = self._exchange_receive(exchange_record)
  File "/home/hbohry/workspace/odoo_17/third-party/edi_oca/models/edi_backend.py", line 601, in _exchange_receive
    raise NotImplementedError()
NotImplementedError

**Comment by simahawk** [comment]
Weird, it sounds like this component is not registered https://github.com/OCA/edi-framework/blob/16.0/edi_storage_oca/components/receive.py

**Comment by Hbohry** [comment]
i already have this component in my code , yet i didn't understand your point on how it can be registered any further 
![edi-receive](https://github.com/user-attachments/assets/5eab496a-1445-47ec-ab33-dcc7b89dadce)

**Comment by simahawk** [comment]
If the module edi_storage is installed properly you shouldn't do anything to register it.
You should debug what's happening on the component lookup.
You can place a pdb [here](https://github.com/OCA/edi-framework/blob/16.0/edi_oca/models/edi_backend.py#L121) and inspect `usage_candidates`. You should find `storage.receive` (thanks to this override https://github.com/OCA/edi-framework/blob/16.0/edi_storage_oca/models/edi_backend.py#L69).
If that's the case, the call to [_matching_components](https://github.com/OCA/edi-framework/blob/16.0/edi_storage_oca/models/edi_backend.py#L69) should give you back that component.
If it's not happening you can inspect the `work.components_registry` to see if the module and the component are registered properly.

**Comment by Hbohry** [comment]
To make sure that our set up is all good , can you provide us with the list of apps i need to install to sucessfully make the automatic import of the ftp files via edi

**Comment by AmbarekTeamdoo** [comment]
Hello,
I am working on the same issue, but something is unclear: does the module support `@GP` as an EDI service provider ?

**Comment by simahawk** [comment]
> To make sure that our set up is all good , can you provide us with the list of apps i need to install to sucessfully make the automatic import of the ftp files via edi

There's nothing else to install. The modules`edi_storage` takes care of defining the component and the configuration for for the storage. 
But wait, I've just seen that the error comes from `/home/hbohry/workspace/odoo_17/...`  but you said you are working on v16.... are you sure your installation is done properly or that you are running odoo w/ the right addons path?

**Comment by simahawk** [comment]
> Hello, I am working on the same issue, but something is unclear: does the module support `@GP` as an EDI service provider ?

What do you mean? I'm not sure this question is pertinent here :)

However. the framework - because it's a framework - does not support any specific provider. It gives you most of the automation you need to talk to any kind of service. You can call webservices or being called via endpoints or you can put and get files from/to an ext storage.
